const quotes = [
      "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
      "Your time is limited, don't waste it living someone else's life.",
      "Every challenge overcome is an opportunity for growth and improvement.",
      "Perseverance is the key to turning dreams into reality.",
      "Don't wait for the perfect opportunity, create your opportunity.",
      "The only person you can control is yourself. Focus on what you can change.",
      "Failures are stepping stones to success.",
      "Never look back unless it's to see how far you've come.",
      "Your determination determines your destiny.",
      "Courage is not the absence of fear, but the ability to move forward in spite of fear.",
      "Life is too short to give up on your dreams. Live each day with passion.",
      "Success is a journey, not a destination.",
      "Your actions speak louder than your words. Act with determination.",
      "Challenges are disguised opportunities. Embrace them and grow.",
      "Be the person you wished you had met when you needed inspiration.",
      "The only limit to our realization of tomorrow will be our doubts of today.",
      "Believe you can and you're halfway there.",
      "Your time is now. Start where you are, use what you have, do what you can.",
      "The only way to do great work is to love what you do.",
      "The harder you work for something, the greater you'll feel when you achieve it.",
      "Dream big and dare to fail.",
      "Success is walking from failure to failure with no loss of enthusiasm.",
      "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
      "It does not matter how slowly you go as long as you do not stop.",
      "You don't have to be great to start, but you have to start to be great.",
      "The road to success and the road to failure are almost exactly the same. The only difference is the direction in which you travel.",
      "The only time to look back is to see how far you've come.",
      "Your positive action combined with positive thinking results in success.",
      "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
      "The future depends on what you do today."
];

export default quotes;